server:
  port: 8080

api:
  service1.url: http://localhost:8081
  service2.url: http://localhost:8082
  service3.url: http://localhost:8083
  service4.url: http://localhost:8084
  service5.url: http://localhost:8085
  service6.url: http://localhost:8086
  service7.url: http://localhost:8087
  service8.url: http://localhost:8088
  service9.url: http://localhost:8089
  service10.url: http://localhost:8090
